https:
  port: ${APP_PORT:-8443}
  hostname: ${APP_HOST:-0.0.0.0}
  tls:
    "default":
      key: ./config/tls/server.key
      cert: ./config/tls/server.pem

admin:
  port: ${APP_ADMIN_PORT:-9876}
  host: ${APP_ADMIN_HOST:-0.0.0.0}

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'

apiEndpoints:
  httpbin:
    host: '*'
    paths:
      - /ip
      - /headers
      - /user-agent
      - /cookies
      - /bearer
      - /response-headers

policies:
  - cors
  - key-auth
  - log
  - proxy
  - rate-limit

pipelines:
  httpbin:
    apiEndpoints:
      - httpbin
    policies:
      - cors:
          action:
            origin: '*'
            credentials: true
            methods: ['GET']
            optionsSuccessStatus: 204
      - key-auth:
          action:
            apiKeyHeaderScheme: Bearer
            disableQueryParam: true
            passThrough: false
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - proxy:
          action:
            name: proxy
            serviceEndpoint: httpbin
            changeOrigin: true
