https:
  port: ${APP_PORT:-8443}
  hostname: ${APP_HOST:-0.0.0.0}
  tls:
    "default":
      key: ./config/tls/server.key
      cert: ./config/tls/server.pem

admin:
  port: ${APP_ADMIN_PORT:-9876}
  host: ${APP_ADMIN_HOST:-0.0.0.0}

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'

apiEndpoints:
  httpbin-anon:
    host: '*'
    methods: ["GET"]
    scopes: []
    paths:
      - /user-agent
      - /cookies
      - /bearer
      - /response-headers
  httpbin:
    host: '*'
    methods: ["GET"]
    scopes: []
    paths:
      - /headers
  httpbin-admin:
    host: '*'
    methods: ["GET"]
    scopes: ["admin"]
    paths:
      - /ip

policies:
  - cors
  - key-auth
  - log
  - proxy
  - terminate

pipelines:
  httpbin-authenticated:
    apiEndpoints:
      - httpbin
      - httpbin-admin
    policies:
      - cors:
          action:
            origin: '*'
            credentials: true
            methods: ['GET']
            optionsSuccessStatus: 204
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - key-auth:
          action:
            apiKeyHeaderScheme: Bearer
            disableQueryParam: true
            passThrough: true
      - log:
          condition:
            name: expression
            expression: "typeof consumer === 'undefined'"
          action:
            message: "unauthorized: autorization[${req.get('Authorization')}], user-agent[${req.get('User-Agent')}]"
      - terminate:
          condition:
            name: expression
            expression: "typeof consumer === 'undefined'"
          action:
            statusCode: 400
            message: ''
      - proxy:
          action:
            name: proxy
            serviceEndpoint: httpbin
            changeOrigin: true
  httpbin-anonymous:
    apiEndpoints:
      - httpbin-anon
    policies:
      - cors:
          action:
            origin: '*'
            credentials: true
            methods: ['GET']
            optionsSuccessStatus: 204
      - log:
          action:
            message: "Anonymous: ${req.method} ${req.originalUrl}"
      - proxy:
          action:
            name: proxy
            serviceEndpoint: httpbin
            changeOrigin: true
